### PR TITLE
Updated ifelse

### PR DESCRIPTION
**Pull request by amitpola**
#43 Updated the Ifelse.dart file with "Nested ifelse and ifelse Ladder along with snippets".

Also refractored the code by creating a function that return the card Widget.

### CODE REVIEW

**Comment by abhitidarbar** [comment]
Hey @amitpola ,can you only add the splash.dart and ifelse.dart in your commit and remove unwanted files. Also,please squash your commit in a single commit if you are working on a single issue. You should only have more than one commit if you are working on more than one issue in a single pr.

**Comment by amitpola** [comment]
Okay

**Comment by amitpola** [comment]
I have deleted the unwanted files but iam unable to remove the commits

**Comment by amitpola** [comment]
I am unable to remove the commits , please help me with that.

**Comment by Siddhant-K-code** [comment]
Just delete those *unwanted* files from your local directory and then push it. all things will be fixed.

**Review by Siddhant-K-code — APPROVED** [review]

**Comment by Siddhant-K-code** [comment]
All things are fine now. @abhitidarbar  You can merge it now.

**Comment by harry-hov** [comment]
> Just delete those _unwanted_ files from your local directory and then push it. all things will be fixed.

Deleting is the solution? Seriously??  

> All things are fine now. @abhitidarbar You can merge it now.

Things are not fine by any means.

**Comment by harry-hov** [comment]
@amitpola 
You commented `splash.dart` in the first commit and undid it in next commit.
I don't understand the reason behind it.
You just can't create problem and fix it in the next commit.

There are 2 possible solution to this situation: 

1. The hard Way 

Revert the changes and edit commits

2. The easy Way

Copy the relevant changes and start fresh on the new branch.

**Pull request closed without merging**
