### PR TITLE
Added structures  in programs and theory; 

### PR DESCRIPTION
**Pull request by ashishbisoi236**
added structures in theory and programs
modified few files for improved visibility in Markdown widget
Function file in programs didnt show 1 line 
Commented one 'Example' because it wasnt showing anything
comment_example

### CODE REVIEW

**Comment by harry-hov** [comment]
Squash your commits @ashishbisoi236

**Comment by harry-hov** [comment]
Also try to address only one issue at a time.
You can always send multiple Pull Requests for multiple issues.

**Review by harry-hov — CHANGES_REQUESTED** [review]
> Squash your commits

**Comment by ashishbisoi236** [comment]
> > Squash your commits

un-necessary commit removed.

**Pull request closed without merging**
