### PR TITLE
Dark/light theme issue#32

### PR DESCRIPTION
**Pull request by savagecarol**
#32 

#Related Issue

# Proposed changes
added switch in drawer.
use of provider and ChangeNotifier.
generated global.dart
little change in main.dart

# Description
generated the bool variable lightDark and use the ThemeDak 

# Screenshots
Screenshot_1607330846
Screenshot_1607330849

### CODE REVIEW

**Review by harry-hov — APPROVED** [review]
Looks good to me. Thanks for working on this. Will be merged soon.

**Comment by savagecarol** [comment]
cool can you assign this issue to me

**Comment by harry-hov** [comment]
> cool can you assign this issue to me

Done

**Comment by abhitidarbar** [comment]
Great Work!!

**Pull request merged**
