### PR TITLE
Added 3 new Programs

### PR DESCRIPTION
**Pull request by manuraj1107**
# Related Issue
- Add more Programs

# Proposed changes
- change 1 - Added program to find armstrong number
- change 2 - Added program to convert decimal to binary
- change 3 - Added program to convert binary to decimal

# Description
- I've Used git add . by mistake , next time i will keep that in mind 

# Screenshots
Screenshot_20201213-183154
Screenshot_20201213-183214
Screenshot_20201213-183230
Screenshot_20201213-183239

### CODE REVIEW

**Comment by abhitidarbar** [comment]
@manuraj1107 can you resolve this merge conflict or you want some help(you will have to wait a day or two for that).

**Comment by manuraj1107** [comment]
Its resolved now!

**Comment by abhitidarbar** [comment]
@manuraj1107 From next time if you made this many commits. The commits can be squashed in single one by using this command.
git rebase -i HEAD~n
n = number of commits to squash
Ex: git rebase -i HEAD~5

**Comment by abhitidarbar** [comment]
> Its resolved now!
@manuraj1107 👍nice

**Pull request merged**
