### PR TITLE
Migrated the Existing App to AndroidX

### PR DESCRIPTION
**Pull request by infiniteoverflow**
# Related Issue
 Issue : #54 

# Proposed changes
Changed gradle.properties file to support AndroidX , and also made minor changes in MainActivity.kt and AndroidManifest.xml to support the same.

# Description
With AndroidX support enabled in the app, the latest packages such as cloud_firestore, etc can run efficiently with the app.

# Screenshots

### CODE REVIEW

**Comment by abhitidarbar** [comment]
Please remove merge conflict . To do this remove .flutter-plugins-dependencies from commit. I don't have android setup for testing so please self verify this .

**Comment by infiniteoverflow** [comment]
I have resolved it , it was required for the migration , thats why it changed during the process and is part of the commit.

**Comment by abhitidarbar** [comment]
> I have resolved it , it was required for the migration , thats why it changed during the process and is part of the commit.

Okay thanks for working on this issue .

**Comment by abhitidarbar** [comment]
> # Related Issue
> Issue : #54
> 
> # Proposed changes
> Changed gradle.properties file to support AndroidX , and also made minor changes in MainActivity.kt and AndroidManifest.xml to support the same.
> 
> # Description
> With AndroidX support enabled in the app, the latest packages such as cloud_firestore, etc can run efficiently with the app.
> 
> # Screenshots
Nice description of issue. Keep up the good work. However if you are not attaching screenshots you can completely remove the topic "Screenshots".

**Pull request merged**
